#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if [[ $(xrandr -q | grep 'DP2 connected') ]]
then
  bspc monitor eDP1 -d I II III IV V 
  bspc monitor DP2 -d VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         3
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a Slack desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a gnome-characters state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#5a15dd"
bspc config normal_border_color         "#282A3A"
bspc config active_border_color         "#C69749"

#
# Autostart
#
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &
#Slack
slack &
#Discord
discord &


# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#Java Fix Intellij

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
